#!/usr/bin/php
<?php
/**
 * @licence GPL-v2
 * Summary :
 * « You may copy, distribute and modify the software as long as
 * you track changes/dates of in source files and keep all modifications under GPL.
 * You can distribute your application using a GPL library commercially,
 * but you must also disclose the source code. »
 *
 * @link https://www.tldrlegal.com/l/gpl2
 * @see LICENSE file
 */
$required = [
    'Const.php',
    'Vendor/autoload.php',
];

require 'dependencies.php';

loadDependencies($required);

try {
    $request = new \App\Library\Io\Request($argv, $argc);
    $app     = new \App\Library\App();
    switch ($request->getAction()) {
        case 'ping':
            $app->ping();
            break;
        case 'synchronize':
            $app->synchronize();
            break;
        case 'update':
            $app->update();
            break;
        case 'help':
        default:
            $actions = ['ping', 'synchronize', 'update'];
            sort($actions);
            echo 'Usage: {' . implode(', ', $actions) . '}', "\n";
    }
} catch (\Exception $e) {
    echo $e->getMessage(), "\n";
    exit(1);
}
