#!/usr/bin/php
<?php
/**
 * @licence GPL-v2
 * Summary :
 * « You may copy, distribute and modify the software as long as
 * you track changes/dates of in source files and keep all modifications under GPL.
 * You can distribute your application using a GPL library commercially,
 * but you must also disclose the source code. »
 *
 * @link https://www.tldrlegal.com/l/gpl2
 * @see LICENSE file
 */

// get
// json post
/*
$data        = ["name" => "Hagrid", "age" => "36"];
$data_string = json_encode($data);
$ch          = curl_init($url);
//echo curl_errno($ch), "\n";
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json', 
            'Content-Length: ' . strlen($data_string)]
);
$data = curl_exec($ch);
echo $data;
$info = curl_getinfo($ch);
print_r($info);
echo "\n";
curl_close($ch);
*/
$required = [
    'Const.php',
    'Vendor/autoload.php',
];

require 'dependencies.php';

loadDependencies($required);

try {
    $request = new \App\Library\Io\Request($argv, $argc);
    $app     = new \App\Library\App();
    switch ($request->getAction()) {
        case 'ping':
            $app->ping();
            break;
        case 'synchronize':
            $app->synchronize();
            break;
        case 'help':
        default:
            $actions = ['ping', 'synchronize', 'update'];
            sort($actions);
            echo 'Usage: {' . implode(', ', $actions) . '}', "\n";
    }
} catch (\Exception $e) {
    echo $e->getMessage(), "\n";
    exit(1);
}
